version: 2.1

orbs:
  unity: game-ci/unity@1.1.0

workflows:
  build-unity-project:
    jobs:
      # Create the Unity activation license file
      # You only need this if you are using the Personal license
      # More info: https://game.ci/docs/circleci/activation#personal-license
      - unity/create-activation-file:
          name: "create-activation-file"

      # Run tests in playmode for Linux, Windows and macOS
      # More info: https://game.ci/docs/circleci/test
      - unity/test:
          name: "test-linux"
          step-name: "Check if the tests run and results are uploaded"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2021.3.9f1"
            resource_class: "medium"
          project-path: "src"
          test-platform: "playmode"
          context: Unity-credentials

      # Build for several platforms using IL2CPP for the scripting backend
      # More info: https://game.ci/docs/circleci/build
      - unity/build:
          name: "build-linux64-il2cpp"
          step-name: "Build StandaloneLinux64"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2021.3.9f1"
            resource_class: "large"
          project-path: "src"
          build-target: StandaloneLinux64
          compress: true
          context: Unity-credentials
